# v1.2 Port mapping and image versioning updated, SQL port mapping removed - thanks Garth  
# v1.1 Volumes updated and network config removed, thanks Josh
# v1.0 Prototype copied from online refs

version: "3"

services:
  db:
    image: mysql:8.0-debian
    volumes:
      - kk_snipe_sqldata:/var/lib/mysql
    environment:
      - TZ=America/Los_Angeles
      - MYSQL_ROOT_PASSWORD=snipedb
      - MYSQL_USER=snipedb
      - MYSQL_PASSWORD=snipedb
      - MYSQL_DATABASE=snipedb
    #deploy:
    #  replicas: 1
    #  placement:
    #    constraints: [node.hostname == gump]

  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - kk_snipe_data:/config
    environment:
      - APP_URL=https://10.10.1.10:4343
      - NGINX_APP_URL=10.10.1.10:443
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipedb
      - MYSQL_USER=snipedb
      - MYSQL_PASSWORD=snipedb
    ports:
      - "4343:443"

volumes:
  kk_snipe_sqldata:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.117.41,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/pools/pool1/snipe_it_mysql"
  kk_snipe_data:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.117.42,rw,noatime,rsize=8192,rsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/pools/pool1/snipe_it_data"

